package gra_osk;

import javax.swing.*;
import java.awt.*;

public class TestLayout {
    private JPanel mainPanel;
    private JLabel question;
    private JRadioButton radioButtonOneRadioButton;
    private JRadioButton radioButton2;
    private JButton changeDatabase;
    private JButton nextQuestion;
    private JPanel questionExtrasPanel;
    private JScrollPane imageContainer;
    private JLabel imageLabel;
    private JPanel answerPanel;
    private JPanel bottomBarPanel;
    private JPanel dbPanel;
    private JLabel dbName;
    private JLabel questionSeqLabel;
    private JLabel correctLabel;
    private JLabel incorrectLabel;


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.setPreferredSize(new Dimension(800, 500));
        question = new JLabel();
        Font questionFont = this.$$$getFont$$$(null, -1, 16, question.getFont());
        if (questionFont != null) {
            question.setFont(questionFont);
        }
        question.setText("Pytanie");
        mainPanel.add(question, BorderLayout.NORTH);
        questionExtrasPanel = new JPanel();
        questionExtrasPanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(questionExtrasPanel, BorderLayout.CENTER);
        imageContainer = new JScrollPane();
        questionExtrasPanel.add(imageContainer, BorderLayout.NORTH);
        imageLabel = new JLabel();
        imageLabel.setText("");
        imageContainer.setViewportView(imageLabel);
        answerPanel = new JPanel();
        answerPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        questionExtrasPanel.add(answerPanel, BorderLayout.CENTER);
        radioButtonOneRadioButton = new JRadioButton();
        radioButtonOneRadioButton.setText("RadioButton One");
        answerPanel.add(radioButtonOneRadioButton);
        radioButton2 = new JRadioButton();
        radioButton2.setText("RadioButton");
        answerPanel.add(radioButton2);
        final JSeparator separator1 = new JSeparator();
        answerPanel.add(separator1);
        bottomBarPanel = new JPanel();
        bottomBarPanel.setLayout(new BorderLayout(10, 0));
        mainPanel.add(bottomBarPanel, BorderLayout.SOUTH);
        dbPanel = new JPanel();
        dbPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        bottomBarPanel.add(dbPanel, BorderLayout.WEST);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$(null, Font.BOLD, -1, label1.getFont());
        if (label1Font != null) {
            label1.setFont(label1Font);
        }
        label1.setText("Baza:");
        dbPanel.add(label1);
        dbName = new JLabel();
        dbName.setText("?");
        dbPanel.add(dbName);
        changeDatabase = new JButton();
        changeDatabase.setText("Zmień…");
        changeDatabase.putClientProperty("hideActionText", Boolean.FALSE);
        dbPanel.add(changeDatabase);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        bottomBarPanel.add(panel1, BorderLayout.EAST);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$(null, Font.BOLD, -1, label2.getFont());
        if (label2Font != null) {
            label2.setFont(label2Font);
        }
        label2.setText("Pytanie: ");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label2, gbc);
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$(null, Font.BOLD, -1, label3.getFont());
        if (label3Font != null) {
            label3.setFont(label3Font);
        }
        label3.setText("Poprawne: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label3, gbc);
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$(null, Font.BOLD, -1, label4.getFont());
        if (label4Font != null) {
            label4.setFont(label4Font);
        }
        label4.setText("Niepoprawne: ");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label4, gbc);
        questionSeqLabel = new JLabel();
        questionSeqLabel.setText("000");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(questionSeqLabel, gbc);
        correctLabel = new JLabel();
        correctLabel.setHorizontalAlignment(4);
        correctLabel.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(correctLabel, gbc);
        incorrectLabel = new JLabel();
        incorrectLabel.setHorizontalAlignment(4);
        incorrectLabel.setText("0");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(incorrectLabel, gbc);
        final JLabel label5 = new JLabel();
        label5.setHorizontalAlignment(2);
        label5.setText("000");
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label5, gbc);
        final JLabel label6 = new JLabel();
        label6.setText("/");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label6, gbc);
        nextQuestion = new JButton();
        nextQuestion.setText("Następne pytanie");
        bottomBarPanel.add(nextQuestion, BorderLayout.CENTER);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(radioButtonOneRadioButton);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) {
            return null;
        }
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
